import React from 'react';
import { RefreshCw, ArrowLeft, Printer } from 'lucide-react';

interface OrderProduct {
  name: string;
  size: string;
  status: 'Ready' | 'Packaging';
  quantity: number;
  price: number;
  tax: number;
  amount: number;
  image: string;
}

interface OrderTimeline {
  message: string;
  details?: string;
  timestamp: string;
  hasInvoice?: boolean;
}

const orderProducts: OrderProduct[] = [
  {
    name: 'Men Black Slim Fit T-shirt',
    size: 'M',
    status: 'Ready',
    quantity: 1,
    price: 80.00,
    tax: 5.00,
    amount: 85.00,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a'
  },
  {
    name: 'Dark Green Cargo Pant',
    size: 'L',
    status: 'Packaging',
    quantity: 3,
    price: 330.00,
    tax: 4.20,
    amount: 334.20,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3'
  },
  {
    name: 'Mid Dark Brown Wallet',
    size: 'S',
    status: 'Ready',
    quantity: 1,
    price: 152.00,
    tax: 5.00,
    amount: 157.00,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93'
  }
];

const timeline: OrderTimeline[] = [
  {
    message: 'The packing has been started',
    details: 'Confirmed by Gaston Lajeunie',
    timestamp: 'April 23, 2024, 09:45 am'
  },
  {
    message: 'The invoice has been sent to the customer',
    details: 'Invoice email was sent to info@customeremail.com',
    timestamp: 'April 23, 2024, 09:41 am',
    hasInvoice: true
  },
  {
    message: 'The invoice has been created',
    details: 'Invoice Generated by Gaston Lajeunie',
    timestamp: 'April 23, 2024, 09:40 am'
  },
  {
    message: 'Order Payment',
    details: 'Using Master Card',
    timestamp: 'April 23, 2024, 09:40 am'
  },
  {
    message: 'Order confirms by Gaston Lajeunie',
    details: 'Order 1 • Order 2 • Order 3 • Order 4',
    timestamp: 'April 23, 2024, 09:40 am'
  }
];

export const OrderDetailss = () => {
  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <div className="flex items-center space-x-4">
          <button className="p-2 hover:bg-gray-100 rounded-lg">
            <ArrowLeft className="h-5 w-5" />
          </button>
          <h1 className="text-xl font-semibold">ORDER DETAILS</h1>
        </div>
        <div className="flex items-center space-x-4">
          <button className="flex items-center space-x-2 px-4 py-2 border rounded-lg hover:bg-gray-50">
            <RefreshCw className="h-4 w-4" />
            <span>Refresh</span>
          </button>
          <button className="flex items-center space-x-2 px-4 py-2 border rounded-lg hover:bg-gray-50">
            <Printer className="h-4 w-4" />
            <span>Print</span>
          </button>
          <button className="px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600">
            Edit Order
          </button>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-6">
        <div className="col-span-2 space-y-6">
          {/* Order Progress */}
          <div className="bg-white p-6 rounded-lg shadow-sm">
            <h2 className="font-semibold mb-4">Progress</h2>
            <div className="relative">
              <div className="h-2 bg-gray-200 rounded">
                <div className="h-full w-3/5 bg-green-500 rounded" />
              </div>
              <div className="absolute top-4 left-0 right-0 flex justify-between">
                <div className="text-center">
                  <div className="text-sm font-medium">Order Confirming</div>
                  <div className="h-1 w-1 bg-green-500 rounded-full mx-auto mt-2" />
                </div>
                <div className="text-center">
                  <div className="text-sm font-medium">Payment Pending</div>
                  <div className="h-1 w-1 bg-green-500 rounded-full mx-auto mt-2" />
                </div>
                <div className="text-center">
                  <div className="text-sm font-medium">Processing</div>
                  <div className="h-1 w-1 bg-orange-500 rounded-full mx-auto mt-2" />
                </div>
                <div className="text-center">
                  <div className="text-sm font-medium">Shipping</div>
                  <div className="h-1 w-1 bg-gray-300 rounded-full mx-auto mt-2" />
                </div>
                <div className="text-center">
                  <div className="text-sm font-medium">Delivered</div>
                  <div className="h-1 w-1 bg-gray-300 rounded-full mx-auto mt-2" />
                </div>
              </div>
            </div>
            <p className="text-sm text-gray-500 mt-12">
              Estimated shipping date: Apr 25, 2024
            </p>
          </div>

          {/* Products */}
          <div className="bg-white rounded-lg shadow-sm">
            <div className="p-6 border-b">
              <h2 className="font-semibold">Product</h2>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                      Product Name & Size
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                      Status
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                      Quantity
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                      Price
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                      Tax
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                      Amount
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {orderProducts.map((product, index) => (
                    <tr key={index}>
                      <td className="px-6 py-4">
                        <div className="flex items-center">
                          <img
                            src={product.image}
                            alt={product.name}
                            className="h-12 w-12 rounded-lg object-cover"
                          />
                          <div className="ml-4">
                            <div className="text-sm font-medium text-gray-900">
                              {product.name}
                            </div>
                            <div className="text-sm text-gray-500">
                              Size: {product.size}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          product.status === 'Ready'
                            ? 'bg-green-100 text-green-800'
                            : 'bg-yellow-100 text-yellow-800'
                        }`}>
                          {product.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-500">
                        {product.quantity}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-500">
                        ${product.price.toFixed(2)}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-500">
                        ${product.tax.toFixed(2)}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-900 font-medium">
                        ${product.amount.toFixed(2)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Timeline */}
          <div className="bg-white p-6 rounded-lg shadow-sm">
            <h2 className="font-semibold mb-6">Order Timeline</h2>
            <div className="space-y-6">
              {timeline.map((event, index) => (
                <div key={index} className="flex">
                  <div className="flex-shrink-0">
                    <div className="h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center">
                      <div className="h-3 w-3 rounded-full bg-blue-600" />
                    </div>
                    <div className="w-0.5 h-full bg-gray-200 mx-auto" />
                  </div>
                  <div className="ml-4 flex-1">
                    <div className="font-medium">{event.message}</div>
                    <div className="text-sm text-gray-500">{event.details}</div>
                    {event.hasInvoice && (
                      <button className="mt-2 text-sm text-orange-500 hover:text-orange-600">
                        Download Invoice
                      </button>
                    )}
                    <div className="text-sm text-gray-500 mt-1">
                      {event.timestamp}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Order Summary */}
        <div className="space-y-6">
          <div className="bg-white p-6 rounded-lg shadow-sm">
            <h2 className="font-semibold mb-4">Order Summary</h2>
            <div className="space-y-4">
              <div className="flex justify-between">
                <span className="text-gray-600">Sub Total:</span>
                <span>$772.00</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Discount:</span>
                <span>-$65.00</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Delivery Charge:</span>
                <span>$30.00</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Estimated Tax (15.5%):</span>
                <span>$29.30</span>
              </div>
              <div className="flex justify-between font-bold">
                <span>Total Amount:</span>
                <span>$712.00</span>
              </div>
            </div>
          </div>

          {/* Payment Information */}
          <div className="bg-white p-6 rounded-lg shadow-sm">
            <h2 className="font-semibold mb-4">Payment Information</h2>
            <div className="flex items-center space-x-3 mb-4">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mastercard-logo.svg/1280px-Mastercard-logo.svg.png"
                alt="Mastercard"
                className="h-8"
              />
              <div>
                <div className="font-medium">Master Card</div>
                <div className="text-sm text-gray-500">**** **** **** 7812</div>
              </div>
            </div>
            <div className="text-sm text-gray-600">
              <div className="flex justify-between mb-2">
                <span>Transaction ID:</span>
                <span>6DN7GS139KS8</span>
              </div>
              <div className="flex justify-between">
                <span>Card Holder Name:</span>
                <span>Gaston Lajeunie</span>
              </div>
            </div>
          </div>

          {/* Customer Details */}
          <div className="bg-white p-6 rounded-lg shadow-sm">
            <h2 className="font-semibold mb-4">Customer Details</h2>
            <div className="space-y-4">
              <div className="flex items-center space-x-3">
                <img
                  src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e"
                  alt="Customer"
                  className="h-12 w-12 rounded-full"
                />
                <div>
                  <div className="font-medium">Gaston Lajeunie</div>
                  <div className="text-sm text-orange-500">info@customeremail.com</div>
                </div>
              </div>
              <div>
                <div className="flex justify-between text-sm mb-2">
                  <span className="text-gray-600">Contact Number:</span>
                  <span>(723) 732-7610-5760</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Shipping Address:</span>
                  <div className="text-right">
                    <p>Wilson Jewelers LTD</p>
                    <p>1343 Hershell Hollow Road,</p>
                    <p>Tukwila, WA 98168,</p>
                    <p>United States</p>
                    <p>(723) 732-7610-5760</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};